orchestrix {
  home-dir = "."
  home-dir = ${?ORCHESTRIX_HOME}

  resolver {
    work-dir = ${orchestrix.home-dir}"/resolver"
    resolution-cache-dir = ${orchestrix.resolver.work-dir}"/cache"
    repository-cache-dir = ${orchestrix.resolver.work-dir}"/local"

    repositories = [ ]
  }

  store {
    cassandra {
      host = ""

      port = 0
    }
  }

  task-queue {
    max-work-timeout = 10m
  }
}

cassandra-journal.contact-points = [ ${orchestrix.store.cassandra.host}":"${orchestrix.store.cassandra.port} ]
cassandra-snapshot-store.contact-points = [ ${orchestrix.store.cassandra.host}":"${orchestrix.store.cassandra.port} ]