orchestrix {
  home-dir = "."
  home-dir = ${?ORCHESTRIX_HOME}

  resolver {
    work-dir = ${orchestrix.home-dir}"/resolver"
    resolution-cache-dir = ${orchestrix.resolver.work-dir}"/cache"
    repository-cache-dir = ${orchestrix.resolver.work-dir}"/local"

    repositories = [ ]

  }
}